### ISSUE TITLE
Discord doesn't display notifications on the taskbar

### ISSUE THREAD

**Issue by willgou** [lawand-dot-io/taskbar#115]
**Describe the bug**
I use Discord on do not disturb (red dot). On the Dock, even while on DND, it used to display a "1" if I got a private message or got tagged in a server. On the taskbar, it always displays my status (DND) even if I have notifications.

**To Reproduce**
1. Go to Discord
2. Tab out of it or click on another window.
3. Receive a private message

**Expected behavior**
I expect it to show a number on top of my Discord icon when I get tagged.

**Desktop (please complete the following information):**
 - Taskbar version 1.2.5
 - OS: 15.1 Sequoia
 - Chip M3 Pro

**Additional context**
My badges are already on (see screenshot)<img width="33" alt="image" src="https://github.com/user-attachments/assets/384d8fe4-5844-4420-8a9f-e98c18fa75c9">
I want it to show a number when I get a notification just like the Dock does.

**Comment by lawand-dot-io** [comment]
Hello. Are you basically saying that the notification badge isn't enough and you want to also see the notification number? If so, that is not yet added to Taskbar..

**Comment by lawand-dot-io** [comment]
Ok, I understand. Will close this bug report and mention it in the existing feature request: https://github.com/lawand-dot-io/taskbar/discussions/55

Cheers
