### ISSUE TITLE
Quitting Taskbar makes Alt-Tab's default keyboard shortcut stop working

### ISSUE THREAD

**Issue by ddang94** [lawand-dot-io/taskbar#15]
**Describe the bug**
Alt-Tab app works in conjunction with the app, but once the taskbar app quits, the alt-tab app breaks and stops working until restarted

**To Reproduce**
1. Have Alt-Tab Open
2. Open Taskbar
3. Quit Task bar
4. command-Tab behavior is now conflicted with the taskbar quitting

**Expected behavior**
Alt-tab app to continue working

**Desktop (please complete the following information):**
 - Taskbar version 1.0.6
 - OS: 14.2.1
 - Chip: Apple M2 Max

**Additional context**
Could be a problem with other apps, but giving Alt-Tab as an example.

**Comment by lawand-dot-io** [comment]
Hello. Thanks for the bug report. What happens to Alttab's behavior when Taskbar is quit? I use Alttab personally and frequently start and quit taskbar and haven't seen an issue. Please tell me more so I figure out the issue :)

**Comment by lawand-dot-io** [comment]
Thanks a lot for the video. This will help me understand this bug. And so I'm guessing the keyboard shortcut you use to trigger alttab is Command (⌘) and Tab (⇥) is that correct? And so not Option/Alt (⌥) and Tab (⇥)

**Comment by lawand-dot-io** [comment]
I reuploaded @ddang94's screen recording for reference:

https://github.com/lawand-dot-io/taskbar/assets/132961914/8eb6f41d-bc9b-4fb5-aa2b-173bed4c8888

**Comment by lawand-dot-io** [comment]
This bug has been fixed in Taskbar version 1.0.8 which is now released.
