### ISSUE TITLE
Incorrectly detecting windows as overlapping Taskbar (on non-main display) and resizing them as a result

### ISSUE THREAD

**Issue by jameszhan9592** [lawand-dot-io/taskbar#21]
**Describe the bug**
With a two-display setup, one placed above the other, when resizing an app window on the bottom display, the bottom of the app window will keep getting resized to the top.

It's really hard to describe with words. Please see the screen recording below.

**To Reproduce**
1. Have two displays connected
2. In display settings, put one of the display above the other
3. Move an app window to the bottom display
4. Double-click the top of the app window to maximize it, OR
5. Drag the bottom edge of the app window down

**Expected behavior**
After the app window is resized, its size will not change until the user resize it again.

**Screen recording**
Please see [this screen recording](https://dropovercl.s3.amazonaws.com/21051c31-86de-4832-91e7-b2e1666f5672/d5eb428b-7195-4e0a-87f8-a78558f8865c/f769bb45-0112-45a1-bd1d-ad39d2293fd9.mp4) of the issue. The screen captured is the bottom display.

**Desktop (please complete the following information):**
 - Taskbar version: 1.0.6
 - OS: Sonoma 14.2.1
 - Chip: Apple M1 Max

**Comment by lawand-dot-io** [comment]
Hi James. Thanks for the bug report. I actually know this bug. This is a side-effect of the "Auto-resize windows when they overlap Taskbar" feature that can be unset in the Advanced tab in preferences. The feature works without issues on a single monitor and is designed to make sure a window that is too large and overlaps Taskbar gets resize as to no longer overlap it. So, until I fix this bug, a temporary solution is to disable that feature and hopefully you find a way to make sure windows aren't being covered by Taskbar.

**Comment by lawand-dot-io** [comment]
Screen recording re-uploaded for reference:
https://github.com/lawand-dot-io/taskbar/assets/132961914/11b7394d-7eaa-4054-9266-9fb1f447260b

**Comment by lawand-dot-io** [comment]
@livinlicious Thanks for the suggestion of the quick fix. That's great

By the way this bug is already fixed in the code base, which means the next version of Taskbar will not have the bug anymore. It should be released in about a week or so.

Cheers

**Comment by lawand-dot-io** [comment]
This bug has been fixed in Taskbar version 1.0.8 which is now released.
