### ISSUE TITLE
Incorrect "Taskbar" task is added to Taskbar after checking for updates

### ISSUE THREAD

**Issue by nopice** [lawand-dot-io/taskbar#24]
**Describe the bug**
"Taskbar" still remains on taskbar after the preferences window was closed

**To Reproduce**
1. Open Taskbar's preferences
2. Go to 'Policies'
3. Click 'Check for Updates...'
4. If you're already on the latest version, you'll get the message "You're up-to-date".
5. Click 'OK' on that alert
6. Close Taskbar's preferences window

**Expected behavior**
"Taskbar" button should be disappeared from taskbar after closing the preferences window.

**Screenshots**
<img width="422" alt="Screenshot 2024-03-05 at 3 36 45 PM" src="https://github.com/lawand-dot-io/taskbar/assets/47148827/ed5cf4b1-1724-43af-bb90-e6dde87f41df">

**Desktop (please complete the following information):**
 - Taskbar version 1.0.6
 - OS: macOS 13.5.1
 - Chip Apple M1

**Additional context**
To fix this, I have to quit Taskbar and relaunch it.

**Comment by lawand-dot-io** [comment]
Hello. Thanks for the bug report. I've seen this edge case before and I can confirm that it happens. I have in mind to fix it at some point 👍

**Comment by lawand-dot-io** [comment]
This bug has been fixed in Taskbar version 1.2.1 which is now released. Closing the ticket.
