### ISSUE TITLE
Incompatibility with the Easy Resize Move tool

### ISSUE THREAD

**Issue by davidgross** [lawand-dot-io/taskbar#54]
**Describe the bug**
When I have more than one app open, and I switch between them using the taskbar, it minimizes a window. 
Example: If I have two apps open, eg: zoom and a browser. And I have the browser focused, and I select zoom, zoom (which is not minimized) will minimize. Also, if I click between the apps, without using the taskbar it minimizes them randomly.

**To Reproduce**
1. open three apps, don't minimize any of them.
2. use one app, then switch to another, the one you switched to will minimize
3. click it back open from the button in the task bar (it will open)
4. click on the app you just unminimized, it will minimize again. (do step 3 and 4 again and it will work, usually)

**Expected behavior**
don't minimize not-minimized windows, when selecting them to bring them into focus.

**Screenshots**

**Desktop (please complete the following information):**
 - Taskbar version: 1.2.1
 - OS: 14.5
 - Chip: M2 Pro (MBP)
 
**Additional context**

**Comment by davidgross** [comment]
This is specific to 1.2.1, 1.0.8 does not do this.

**Comment by lawand-dot-io** [comment]
@davidgross Thanks a lot for reporting this. I tried to reproduce the bug now and I can't. I can go through the code and try to figure out why this is happening, but if you can make a quick screen recording (starting from before you open taskbar) that would be a great help :) In any case I will try to figure out this bug

**Comment by davidgross** [comment]
Interesting, after downgrading to 1.0.8 and back up to 1.2.1 it's not doing it... If I get it to do it again I'll make a video.

**Comment by lawand-dot-io** [comment]
That would be very helpful. By the way do you remember if this happened when you just did the upgrade to 1.2.1? There is a known bug where the first time Taskbar is open or the first time you enter a workspace, and there are windows already open, the currently focused window might be incorrectly set, and it only becomes correct after the first window switch. This might be related to that..

**Comment by davidgross** [comment]
It was a fresh install, I got the MBP, and I installed 1.2.1 from nothing.

**Comment by lawand-dot-io** [comment]
Ok. Anyway, I will keep this bug open for now and try to investigate it more. I would highly appreciate if you tell me if it happened again and enjoy the new version of Taskbar :)

**Comment by davidgross** [comment]
So this is still happening, it's super intermittent, so I haven't been able to make a screen recording of it. Because it's my work computer, it's going to take some thinking for me to make a screen recording with my work stuff redacted. It seems to happen more after several sleep-wakeup cycles on the laptop, even if they are all in the same day. And it almost never happens after a reboot for several hours. Once the laptop has slept/hibernated/etc a time or two the odds of the behavior occurring goes up (but is not a guarantee)

**Comment by lawand-dot-io** [comment]
@davidgross I appreciate that you're giving me some more details. I think I should prioritize this bug and try to figure it out. In the meantime you should probably downgrade to 1.0.8 so that you're work is not effected

**Comment by lawand-dot-io** [comment]
@davidgross are you still using 1.0.8? if so, it's gonna expire in 10 days so I gotta extend 1.0.8 for you

**Comment by davidgross** [comment]
I am still using 1.0.8, though it's been doing the same behavior the last week or so, so it's not an issue specific a version.

**Comment by lawand-dot-io** [comment]
@davidgross hmm. perhaps this is the result of some interaction between Taskbar and another app you have running, do you have other apps that manage window or resize them etc?

**Comment by davidgross** [comment]
That's a good point, I use Better Touch Tool (https://folivora.ai/) and Easy Resize Move (https://github.com/dmarcotte/easy-move-resize). Both do deal with window resizing. BTT does window "snapping" like drag to the side for half screen, drag to the top for maximize, and ERM handles mouse+modifires to move/resize windows. I'll try turning both off tomorrow, and see if that solves the issue. I'm suspicious of BTT now that I think about it.

**Comment by davidgross** [comment]
Granted, I've been using BTT and ERM for several years, without issue, until I started using Taskbar, so it's some sort of interaction with one (or both) of them with Taskbar.

**Comment by lawand-dot-io** [comment]
Yeah, the reason I am asking about whether or not there's an interaction is that you said the behavior also happens when you switch between windows by clicking on the windows and not by using their tasks in Taskbar. Another thing you can try is that once the behavior starts happening, you can try to quit Taskbar and try to click between the windows and see if the bug continues to happen.

**Comment by davidgross** [comment]
Yeah, makes sense, current findings:
1) when it's doing it, quitting taskbar does fix it, until I start it back up (at which time some times starts doing it again, and some times it waits for a while)

2) With BTT and ERM turned off, the issue has not occurred at all. I'm going to try turning BTT back on and see what happens.

**Comment by davidgross** [comment]
With BTT on, and ERM off, I have not had the behavior, so it's something with ERM and Taskbar.

**Comment by lawand-dot-io** [comment]
Thanks for all this input, hopefully I'll be able to figure out this bug

**Comment by lawand-dot-io** [comment]
@davidgross any updates on this? It's really hard to understand the bug without a screen recording. I tried installing the easy resize/move app and running it along with taskbar for the past month and never saw behavior like the one you described. if you have not given up on this, i need a screen recording with mouse clicks shown. thanks

**Comment by lawand-dot-io** [comment]
another thing that can help is a screenshot of the applications folder to see all the apps that are installed so that i try installing all of them and see if the bug starts happening for me

**Comment by davidgross** [comment]
@lawand-dot-io I can confirm it's the [Easy Resize Move](https://github.com/dmarcotte/easy-move-resize) tool fighting with Taskbar, I've had it off/not installed for a while, and not had the issue at all.

If you install ERM and Taskbar and just leave them running for a while, it will start doing the minimizing at app-switch times.

**Comment by lawand-dot-io** [comment]
@davidgross ok that's great news. I had ERM installed and running alongside Taskbar for a long time and never had any issues. Can you maybe screenshot the ERM menubar menu since it shows exactly how the configurations are. Maybe I need to match your config. Thanks and it's good to hear you continue to use Taskbar without issues

**Comment by lawand-dot-io** [comment]
Closing this issue and considering Taskbar incompatible with the Easy Resize Move tool
