### ISSUE TITLE
Freezing on opening.

### ISSUE THREAD

**Issue by GreenBioTheGreat** [lawand-dot-io/taskbar#58]
The bug is that when I open the app, "Taskbar," it becomes unresponsive. Not only that, it states that I did not grant thumbnails, but I granted it full disk access.

1. Open the app.

I expect the app once opened to automatically freeze without at least putting the taskbar back in the screen.

 - Taskbar V. 1.2.1
 - OS: macOS 15 Sequoia
 - Chip Apple Silicon, M1

**Comment by lawand-dot-io** [comment]
Hello. Thanks for using Taskbar. macOS Sequoia is still in beta so I can't support it yet as it might be unstable and also might introduce new changes before the official release, so I can't say anything about the freezing issue.

As for asking for screen recording permission even though you already granted it, this is a new change introduced in Sequoia where the system will ask you to re-confirm the screen recording permission every time you launch the app. This will also happen with any other app that requires the screen recording permission. You can always disable the thumbnails feature and revoke the permission if you don't want to see this promot when starting Taskbar.

Let me know if you have any further questions :)

**Comment by lawand-dot-io** [comment]
I'll be closing this bug report since the bug happened on an unsupported and buggy beta version of macOS. Will look into this again if it happened with the released version of macOS sequoia.
