### ISSUE TITLE
Enable thumbnails on MacOS 15 Beta does not work

### ISSUE THREAD

**Issue by absurf23** [lawand-dot-io/taskbar#62]
Enable thumbnails on MacOS 15 Beta does not work - when the permission is granted for screen recording in settings, the taskbar app does not see this and reports status "not granted". Thumbnails has to be turned off in taskbar app in order to proceed and get the app to work otherwise.

**Comment by lawand-dot-io** [comment]
Hello. Thanks for the bug report. Unfortunately I cannot support beta versions of macOS as anything could change until the official release. I will keep this bug open and let's see if this is still happening when MacOS 15 is out of beta :)

**Comment by absurf23** [comment]
Understand, just reporting it in case you might have known of it and had a workaround. I'll try to test again after GA release of Sequoia. Enjoy the Taskbar app and use it daily - ty!

**Comment by lawand-dot-io** [comment]
That's fair. Yeah for me I tried Taskbar a bit on Sequoia and didn't see this issue, that's why I think it's just due to the beta being constantly updated, so I'll wait for the release to do a proper test and see what changes I need to make to Taskbar to make it work with that version :)

**Comment by lawand-dot-io** [comment]
@absurf23 Closing this ticket since I tested Taskbar with macOS 15.0 and didn't experience this issue. Feel free to reopen it in case the issue still occurs with you. thanks
