### ISSUE TITLE
Applications disappears from the task bar randomly.

### ISSUE THREAD

**Issue by dinbtechit** [lawand-dot-io/taskbar#73]
**Describe the bug**
Applications disappears from the task bar randomly.

**To Reproduce**
1. Taskbar

**Expected behavior**
Running applications should remain in the taskbar

**Screenshots**
![image](https://github.com/user-attachments/assets/d93e77f8-7da9-458d-b6b0-9cee6258fa3f)
Sometimes the above 2 applications randomly disappears.

**Desktop (please complete the following information):**
 - Taskbar version [e.g. 1.0] - 1.2.1
 - OS: [e.g. macOS 13.3.1] - Sonoma 14.5 (23F79)
 - Chip [e.g. Apple M1] - M1

**Additional context**
N/A

**Comment by lawand-dot-io** [comment]
Hello. Thanks for the bug report. Can you tell me the names of those two applications (the .app files in the Applications folder) as well as a link to where I can download them so that I can try this bug for myself? Thanks

**Comment by dinbtechit** [comment]
Hi, they are jetbrain's IDE's.. However, I don't think they are application specific. It happens to Microsoft Word, Discord, MS Teams, slack, etc etc.

Notice I have a lot of running applications on my dock. However, only a few of them show up on my taskbar. I would think it should show all the running apps.

![image](https://github.com/user-attachments/assets/f8e48094-b4f9-4613-b714-e85e1050dd73)

vs 

![image](https://github.com/user-attachments/assets/aa2f1418-d2fd-4ebb-af24-62b7397c5f5e)

**Comment by lawand-dot-io** [comment]
Oh maybe I know what's happening, do any of those apps have open windows? Taskbar only shows apps that have open windows

**Comment by dinbtechit** [comment]
ahh..  I see. Is there by any chance can we keep all the running applications in the taskbar even the ones that do not have a window?

**Comment by lawand-dot-io** [comment]
There's a feature request for keeping windowless apps shown. feel free to upvote it: https://github.com/lawand-dot-io/taskbar/discussions/70

**Comment by lawand-dot-io** [comment]
And by the way, so you can confirm that there is no bug? All the apps you mentioned are not shown don't have any windows?

**Comment by dinbtechit** [comment]
Confirmed none of the apps had a running window. But #70 would be a critical feature for me. Apps like Teams, Discord, Slack, outlook don't always have running window. However, it would be nice to see their notifications on the taskbar... if possible.

Closing this ticket.

**Comment by lawand-dot-io** [comment]
@dinbtechit how about using the "Keep in Taskbar" option from the context menu? I guess you'll be missing the notifications but it's a start

**Comment by lawand-dot-io** [comment]
And there's a feature request to "Show notifications for app icons (added using the "Keep in Taskbar" option)": https://github.com/lawand-dot-io/taskbar/discussions/75

**Comment by dinbtechit** [comment]
> @dinbtechit how about using the "Keep in Taskbar" option from the context menu? I guess you'll be missing the notifications but it's a start

Right, I am using "Keep in Taskbar". But be nice to see the #75 implemented. 

Btw.. I would love to contribute to this project if you need a helping hand. Let me know.
