### ISSUE TITLE
No response when clicking on tasks to switch to their windows

### ISSUE THREAD

**Issue by fires3as0n** [lawand-dot-io/taskbar#78]
**Describe the bug**
At some circumstances clicking on the items stops switching the apps

**To Reproduce**
1. Click on the item in the taskbar

**Expected behavior**
Window of clicked app opens

**Actual behavior**
Window of clicked app does not open

**Screenshots**

https://github.com/user-attachments/assets/22bca3bd-0bd2-41d0-9c0b-d4539992b075

**Desktop (please complete the following information):**
- Taskbar version [1.2.1]
- OS: [12.6.2]
- Chip [Intel i7]

**Comment by lawand-dot-io** [comment]
Thanks for the bug report. did this issue happen more than once? sometimes it's a random macOS bug that it resolved by a restart or going to sleep and back. please let me know so I can understand this more

**Comment by fires3as0n** [comment]
Tried:
 - quit app, launch again
 - sleep, wake
 - restart
 - shut down, wait, turn on
None of that  helped.

**Comment by fires3as0n** [comment]
Additional steps tried:

- upgrading MacOS version 12->14
- disconnecting external monitors to try from built in display
- resetting app settings

None of that helped as well

**Comment by lawand-dot-io** [comment]
Hello. I've been busy the l

**Comment by lawand-dot-io** [comment]
Hello. I've been busy the last couple of days and didn't get a chance to start thinking about this bug. One question comes to mind is that obviously this wasn't happening when you first started using Taskbar, right? When did it start and why? Did you install some app or change something? I'm wondering why this bug started happening

**Comment by fires3as0n** [comment]
I was thinking about that myself, but I have no idea, I was just using it as usual. During several reboots it a recent days it even started to work when I had only one window with MacOS settings there. But then I launched the web browser and the whole thing became unresponsive again.

**Comment by lawand-dot-io** [comment]
@fires3as0n try removing both permissions for Taskbar. That might fix the problem

**Comment by lawand-dot-io** [comment]
So, accessibility and screen recording

**Comment by lawand-dot-io** [comment]
@fires3as0n did you get a chance to try that?

**Comment by qwkkze** [comment]
Sorry for the long reply, well if i try to remove the permissions - it is not working at all.

**Comment by lawand-dot-io** [comment]
@qwkkze are you the same person that reported this bug? I think it's a different account. In any case I meant that the solution might be to remove the permissions then grant them again. This might solve the macOS bug that makes Taskbar not respond to clicks. Did you try that?

**Comment by fires3as0n** [comment]
I am sorry, I have to use several accs to split github repos that I use for myself and the ones that I give to my students. I have deleted the comment to avoid confusion. The steps that i have done:

1. Remove the permissions as you told - the app stops to work
2. Remove permissions + delete the app + reinstall the app + enable permissions + reset settings - the bug still persists

What I have noticed is that I can actually bring window to front by right click-> minimize + right click->maximize, also I can close windows with middle click if the setting is enabled, so the taskbar itself responds to the clicks, but not for the left click.

I thought it could be mouse related, I have tried disconnecting everything from the laptop and using the touchpad, but unfortunately that did not work either. I have literally no idea what else can I try.

**Comment by lawand-dot-io** [comment]
@fires3as0n Thanks for the information. I have to apologize that you went through all this trouble, I feel bad you are experiencing this bug. In any case, I might have found a solution. Would you please try this update:

https://www.dropbox.com/scl/fi/5nudgn9i8k18hzw7p1hed/Taskbar-1.2.2.zip?rlkey=5bmvsez6e67ayvez3rleerz0h&st=en6xkkux&dl=1

Simply download the zip file then extract the .app file inside it into the Applications folder (over-writing the existing Taskbar version)

This version only contains the bug fix, so should be as stable as the official version. Let me know if it worked. Thanks

**Comment by fires3as0n** [comment]
I have tried the new version and confirm that the fix works. Thank you so much!

Looking forward for multi monitor support and vertical layout. But this Mac Taskbar is already better than windows has (after they killed taskbar in v11). What I also like is that you don't re-implement the wheel by making start menu like e.g. "Sidebar" does. Because launchpad + spotlight + dock already make 90% of its functionality, but fast tasks witching is what mac lacks a lot.

Your taskbar is literally a time saver, I can't understand how do people live without it.

**Comment by lawand-dot-io** [comment]
@fires3as0n That's great to hear. Don't thank me, I still feel bad that you had to go through all this trouble to try to fix the bug. I'm glad to hear Taskbar is working again for you. I'm still wondering why this bug started happening in the first place, but I think my fix will not make it happen again. Please let me know if this bug or any other bug was happening. 

The new version is in development now and will most likely include multi-monitor. I agree that using the launchpad feels more integrated with the OS but a lot of people asked for a custom start menu so I might add it at some point (but of course will keep the option to use the default Launchpad)

Thanks again for the positive feedback, it's very encouraging. Cheers and have a nice day

**Comment by lawand-dot-io** [comment]
This bug is now fixed in the new release of Taskbar, which is version 1.2.5
