### ISSUE TITLE
Can not show the window on clicking the icon in the taskbar

### ISSUE THREAD

**Issue by ritim** [lawand-dot-io/taskbar#88]
**Describe the bug**
I can't open the window when I click the icon in the taskbar. It must to use Fullscreen and then open the app window.

**To Reproduce**
1. Go to task bar.
2. Click on app icon.
3. Not working to open app window.

**Expected behavior**
Open the app window when I click app icon.

**Screenshots**

**Desktop (please complete the following information):**
 - Taskbar version : 1.2.1
 - OS: macOS Sonoma 14.4
 - Chip : Apple M3 Max

**Comment by lawand-dot-io** [comment]
@ritim Hello. Are you still experiencing this issue?

**Comment by lawand-dot-io** [comment]
@ritim I will close this report for now. Feel free to reopen it in case this issue is still happening. Thanks

**Comment by ritim** [comment]
Hi Taskbar,

Sorry for late response.

Now it's working well on taskbar 1.2.2 .

Thank you for your patch version.

lawand-dot-io ***@***.***> 於 2024年10月13日 週日 上午7:03寫道：
