### ISSUE TITLE
All taskbar items duplicated when sharing screen in MS Teams 

### ISSUE THREAD

**Issue by OlegLoewen** [lawand-dot-io/taskbar#89]
**Describe the bug**
All taskbar items duplicated when sharing screen in MS Teams.

Issue started to appear after updating to macOS Sequoia 

**To Reproduce**
1. Go to MS Teams
2. Call someone
3. Share your desktop
4. Check number of items in taskbar

**Expected behavior**
Taskbar items are the same.

**Actual behavior**
Every taskbar item is twice in the taskbar.

**Screenshots**
<img width="2553" alt="image" src="https://github.com/user-attachments/assets/98d78e2f-6f83-4ad4-914c-8f006143c611">

**Desktop (please complete the following information):**
 - Taskbar version 1.2.1
 - OS:  macOS 15.0 (24A335)
 - Chip Apple M3

**Additional context**
None

**Comment by lawand-dot-io** [comment]
@OlegLoewen ok great, glad that the issue is fixed. I have to say by the way, whether they are duplicated or not, the number of windows you have open is mind boggling. I guess you agree that doing such multitasking using the Dock isn't as easy as it is when using Taskbar :) cheers
