### ISSUE TITLE
App expired on Jan 1, 1482

### ISSUE THREAD

**Issue by llerickll** [lawand-dot-io/taskbar#96]
**Describe the bug**
After opening the app first time, it said "expires on Jan 1, 1482"

**To Reproduce**
Open the app first time.

**Expected behavior**
It should show "expires on Jan 1, 2025"

**Screenshots**
<img width="668" alt="SCR-20241026-mqxx-2" src="https://github.com/user-attachments/assets/0b013718-b0a4-4b02-afa9-3c1c9d7d5766">

**Desktop (please complete the following information):**
 - Taskbar version: 1.2.5
 - OS: macOS 15.0.1
 - Chip: Apple M1

**Comment by lawand-dot-io** [comment]
Hello. Thanks for the bug report. I feel bad your experiencing this bug, I haven't seen this issue before. Can you help more figure it out? One thing I can ask is a screenshot of your system preferences Date & Time tab which looks something like this:
<img width="718" alt="Screenshot 2024-10-27 at 01 30 00" src="https://github.com/user-attachments/assets/d2eb3849-43c6-4b43-97e8-969bbaf80149">

**Comment by lawand-dot-io** [comment]
Another question, do you have any apps installed that could changes something related to the default time and date? Thanks

**Comment by llerickll** [comment]
<img width="827" alt="01" src="https://github.com/user-attachments/assets/7f14a9e7-3b88-4032-bbc3-b1f4ecc020e7">
Date and time shows 27 Oct 2567 because I choose Calendar: "Buddhist" according to my region.
<img width="811" alt="02" src="https://github.com/user-attachments/assets/4b6edd58-606e-4c60-b037-5d7a82acee14">
After I change Calendar from "Buddhist" to "Gregorian", Date and time shows 27 Oct 2024 and Taskbar app run normally.
<img width="827" alt="03" src="https://github.com/user-attachments/assets/4773c100-b0e7-4c85-baa3-37324d21a260">
The problem is solved !! Thank you for your information.

**Comment by lawand-dot-io** [comment]
Ok great, I'm happy the issue is solved. Enjoy Taskbar
